# 1. Array Creation:

## Create a 1-dimensional array of integers from 1 to 10.

In [1]:
import numpy as np

In [5]:
array = np.arange(1, 11)

In [6]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


## Create a 2-dimensional array with random float values of shape (3, 4).

In [7]:
array=np.random.rand(3,4)

In [8]:
print(array)

[[0.00459069 0.01898674 0.77761439 0.52276666]
 [0.01748038 0.00351434 0.41318861 0.28285278]
 [0.80754324 0.63880151 0.41653248 0.78000567]]


## Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [9]:
array = np.zeros((2, 3, 4))
print(array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# 2. Array Operations:

## Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])


In [11]:
addition = array1 + array2
print("Addition:", addition)


Addition: [ 7  9 11 13 15]


In [12]:
subtraction= array1-array2
print("Subtraction:",subtraction)

Subtraction: [-5 -5 -5 -5 -5]


In [13]:
multiplication = array1*array2
print("Multiplication:",multiplication)

Multiplication: [ 6 14 24 36 50]


In [14]:
division = array1/array2
print("Division:",division)

Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])


In [22]:
mean_value = np.mean(arr)
print("Mean:", mean_value)

Mean: 6.5


In [23]:
median_value = np.median(arr)
print("Median:",median_value)

Median: 6.5


In [24]:
standard_deviation = np.std(arr)
print("Standard Deviation:", standard_deviation)

Standard Deviation: 3.452052529534663


## Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).

In [25]:
arr_1dimensional = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [26]:
arr_2dimensional = arr_1dimensional.reshape(3, 4)
print(arr_2dimensional)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 3. Array Indexing and Slicing:

## Extract the first row and last column of a 2-dimensional array.

In [27]:
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [28]:
first_row = array_2d[0, :]
print("First row:", first_row)

First row: [1 2 3]


In [29]:
last_column = array_2d[:, -1]
print("Last column:", last_column)

Last column: [3 6 9]


## Reverse the order of elements in a 1-dimensional array.

In [30]:
reversed_arr = array_2d[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [[7 8 9]
 [4 5 6]
 [1 2 3]]


## Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [31]:
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


In [32]:
threshold = 5

In [34]:
selected_elements = array_2d[array_2d > threshold]
print("Selected elements:", selected_elements)

Selected elements: [6 7 8 9]


# 4. Array Broadcasting:

## Add a scalar value to each element of a 2-dimensional array.

In [35]:
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [40]:
scalar_value = 11

In [42]:
result_array = array_2d + scalar_value
print("Result array:",result_array)


Result array: [[15 16 17]
 [18 19 20]]


## Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [43]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[4, 5, 6],
                   [7, 8, 9]])

In [49]:
result_array = arr_1d * arr_2d


In [50]:
print("Result array:",result_array)


Result array: [[ 4 10 18]
 [ 7 16 27]]


# 5. Linear Algebra:

## Calculate the dot product of two 1-dimensional arrays.

In [52]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [53]:
dot_product = np.dot(array1, array2)
print("Dot product:", dot_product)


Dot product: 32


## Compute the matrix multiplication of two 2-dimensional arrays.

In [54]:
array1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

array2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])


In [55]:
result_dot = np.dot(array1, array2)
print("Matrix multiplication using np.dot():",result_dot)



Matrix multiplication using np.dot(): [[ 58  64]
 [139 154]]


In [57]:
result_operator = array1 @ array2
print("Matrix multiplication using @ operator:",result_operator)



Matrix multiplication using @ operator: [[ 58  64]
 [139 154]]


In [ ]:
V

In [58]:
matrix = np.array([[1, 2],
                   [6,5]])


In [59]:
determinant_matrix = np.linalg.det(matrix)
print("Determinant:", determinant_matrix)


Determinant: -2.0000000000000004


In [60]:
if determinant_matrix != 0:
    # Compute the inverse of the matrix
    inverse_matrix = np.linalg.inv(matrix)
    print("Inverse matrix:")
    print(inverse_matrix)
else:
    print("The matrix is singular, and its determinant is zero. Inverse does not exist.")

Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
